---
title: "About"
---

I am Sophie Lee, a statistician with a passion for showing everyone that statistics does not need to be scary! 

Over the past 10 years, I have written and delivered statistics and R programming courses to people from many different backgrounds and levels of experience. My courses have been attended by a wide range of people, from researchers and university students, to medical doctors and surgeons, to social scientists and anthropologists, to data scientists and economists. I have consistently received excellent feedback about my ability to explain complex ideas in simple terms, the inclusive nature of my courses which encourages active participation, and the detailed materials that I provide participants after all of my courses.

My research interests lie in spatial data analysis, planetary health, Bayesian modelling approaches, and epidemiology. During my PhD, I used a combination of existing and novel spatial statistical modelling approaches to better understand the drivers of dengue re-emergence and expansion in Brazil. These models were informed by data from a range of epidemiological, demographic and climatic spatial datasets. I used R software to carry out these analyses and published public online repositories alongside research papers containing detailed code to reproduce model results. 

Besides work, I love to travel and cook. On the weekends, I can usually be found tending to my little greenhouse in my Sheffield garden, baking cakes, or hiking up hills in the Peak District. 